name: Docker Build and Push to GHCR

on:
  push:
    branches:
      - main  # Puedes cambiarlo al branch que prefieras (main/master/develop)

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      # Paso 1: Checkout del repositorio
      - name: Checkout Repo
        uses: actions/checkout@v4

      # Paso 2: Login a GitHub Container Registry
      - name: Login a GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Paso 3: Extraer metadatos para etiquetar la imagen Docker
      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.actor }}/medicalofficewebclient

      # Paso 4: Construir y subir la imagen Docker
      - name: Build & Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: . 
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
