import localFont from "next/font/local";
import Script from "next/script";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Medical Office App",
  description: "Generated by Raptor057",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>

        {/* Script externo: Ripple */}
        <Script
          src="https://unpkg.com/@material-tailwind/html@latest/scripts/ripple.js"
          strategy="afterInteractive"
        />

        {/* Script Inline: variable de entorno dinámica */}
        <script
          dangerouslySetInnerHTML={{
            __html: `window.NEXT_PUBLIC_API_URL="${process.env.NEXT_PUBLIC_API_URL}"`,
          }}
        />

        {/* Layout UI */}
        <main>{children}</main>
      </body>
    </html>
  );
}
